### ISSUE TITLE
Link::setClass() should be renamed to addExtraClass()

### ISSUE THREAD

**Issue by wernerkrauss** [gorriecoe/silverstripe-link#11]
This way you can inject custom css classes in the templates by calling e.g.

`$Me.addExtraClass('text-gray-700')}`

It works with `setClass()`, but IMHO there should be consistency with SilverStripe built in naming.

**Comment by gorriecoe** [comment]
Commit https://github.com/gorriecoe/silverstripe-link/commit/2e5b613117ed20fe2a6f49c9b472df064a8fdce0 should now resolve this.
