### ISSUE TITLE
No way to natively disable linking to a folder

### ISSUE THREAD

**Issue by GuySartorelli** [gorriecoe/silverstripe-link#14]
Most of the time, when the link type is "File on this website", the intention is for content authors to link specifically to files, and no to folders - but either through misunderstanding or mis-clicking, currently content authors _can_ link to folders.

TreeDropdownField allows passing in a 'DisableFunction' to set certain nodes as disabled (i.e. not selectable). I propose setting a function that will disable all folders.
This should of course be configurable (be it globally via .yml config, or per link field through some sort of linkfield configuration) in case linking to folders is intended for some application (and to avoid breaking backwards compatibility).

I am happy to submit a pull request to resolve this - it's what I'm working on right now in an extension for an application I'm working on. Just let me know your preferred configuration out of the above (or other) options.

**Comment by gorriecoe** [comment]
Feel free to make a PR.  I could be wrong but think it makes sense to disable it by default as I never intended to link to a folder in the first place.  Aka this is a bug.

**Comment by GuySartorelli** [comment]
I agree that it would ideally be disabled by default - the only problem with that is that it's technically a breaking change since (regardless of original intentions) someone may be using the Link model to intentionally link folders. In theory it would be a major version release.
That said I'll submit a PR later today. Unless you indicate otherwise I'll make it configurable globally via .yml, and disabled by default.

**Comment by GuySartorelli** [comment]
I have made a PR (#15) to address this.

**Comment by GuySartorelli** [comment]
PR Merged. Closing this issue.
