### ISSUE TITLE
Can't reach LinkSiteTree cms fields (e.g SiteTreeID) via extensions

### ISSUE THREAD

**Issue by jakxnz** [gorriecoe/silverstripe-link#20]
Versions

```
gorriecoe/silverstripe-link   1.3.0
```

**Issue**

I can't use my own extension to reach the cms fields created by `LinkSiteTree`

**Steps to recreate**

1. Configure an extension at the app-level
2. In the extensions's `updateCMSFields()` attempt to access a field named `SiteTreeID`

**Expected behaviour**

The field can be reached by name or recursively

**Actual behaviour**

The field can't be reached. The `LinkSiteTree` extension is executed after the app-level extension

**Suggestion solution**

Name _all_ of the configs in `~/vendor/gorriecoe/silverstripe-link/_config/config.yml`, so that downstream users can sequence their configs `After` this module's

e.g

**~/app/_config/config.yml**
```
---
Name: appconfig
After:
  - '#linkconfigcms'
--- 
```

**Comment by elliot-sawyer** [comment]
This was merged in #21
