### ISSUE TITLE
GraphQL classes not compatible with upcoming GraphQL 4 module

### ISSUE THREAD

**Issue by bummzack** [gorriecoe/silverstripe-link#23]
The new GraphQL 4 module removed the need for some of the classes, such as `QueryCreator`. Therefore the installation of this module next to GraphQL 4 will result in fatal errors during `dev/build`

Maybe the issue could be solved similarly to the `asset-admin` module, where they moved these classes into a `_legacy` folder: https://github.com/silverstripe/silverstripe-asset-admin/tree/1/_legacy/GraphQL and prevented class loading like this: https://github.com/silverstripe/silverstripe-asset-admin/blob/1/_legacy/GraphQL/ReadFileUsageQueryCreator.php#L14

I'm unsure about the  `ScaffoldingProvider` (https://github.com/gorriecoe/silverstripe-link/blob/master/src/models/Link.php#L32) though, as it is no longer available in the latest version.

**Comment by bummzack** [comment]
The upgrade-path for scaffolders is described as follows: https://docs.silverstripe.org/en/4/developer_guides/graphql/upgrading/#scaffoldingproviders-are-now-schemaupdaters

Not sure if that can be accomplished within the same codebase though (eg. creating a module that is compatible with both GraphQL 3 and 4). Maybe @unclecheese knows…

**Comment by robertvanlienden** [comment]
Experienced issues when updating to SS4.10. Reported them in `silverstripe-linkfield`, see the issue below;
https://github.com/gorriecoe/silverstripe-linkfield/issues/33

**Comment by elliot-sawyer** [comment]
This should be fixed now in #24

**Comment by bummzack** [comment]
Lovely, thanks a lot. I've been using UncleCheese's fork until now, glad this is now merged/fixed. ❤️
