### ISSUE TITLE
Hacktoberfest: If you would like, can you please add the 'hacktoberfest' topic to the repo?

### ISSUE THREAD

**Issue by chrispenny** [gorriecoe/silverstripe-link#25]
https://hacktoberfest.digitalocean.com/
https://hacktoberfest.digitalocean.com/resources/maintainers

![Screen Shot 2021-10-05 at 10 06 58 AM](https://user-images.githubusercontent.com/505788/135925016-1fb36a91-44d8-4bc2-951e-a1e58dfff487.png)

**Comment by elliot-sawyer** [comment]
Not an issue, thanks for the heads up for next time!
