### ISSUE TITLE
style reverting to default on save

### ISSUE THREAD

**Issue by korthjp17** [gorriecoe/silverstripe-link#8]
We were experimenting with this module a little bit and trying to add different button styles. They show up in the CMS, but when it gets changed and hit the save button, it reverts back to the default style. We are running the current version 1.2.4

**Comment by gorriecoe** [comment]
This should resolved in https://github.com/gorriecoe/silverstripe-link/commit/80a264c9ba3b76f8934a92c26311bdbf20a0c9ba
